name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: 
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: adopt
          cache: gradle

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          path: build/libs

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: github.event_name == 'release'
        env:
          GHR_PATH: build/libs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
